#!/bin/bash
SCRIPT_DIR=`CPWD=$(pwd);cd $(dirname \$0);pwd;cd \$CPWD`
SCRIPT_NAME=`basename $0 | perl -pe 's/\.[^\.+]+$//g'`

# Activate the virtual environment
source "${SCRIPT_DIR}/.venv/bin/activate"

# Run the Python script
python "${SCRIPT_DIR}/${SCRIPT_NAME}.py" $@
